[package]
name = "docstring"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.4", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.20"
text_io = "0.1.12"
